import pygame as pg

LCD_CLEAR_EVENT = pg.USEREVENT + 1
LCD_INIT_EVENT = pg.USEREVENT + 2
LCD_DISPLAY_EVENT = pg.USEREVENT + 3
LCD_ROTATION_EVENT = pg.USEREVENT + 4
LCD_DRAW_STRING_EVENT = pg.USEREVENT + 5
LCD_DRAW_QR_CODE_EVENT = pg.USEREVENT + 6

SCREENSHOT_EVENT = pg.USEREVENT + 7
